# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(max_length=400)),
                ('item_rate', models.FloatField()),
                ('bags', models.IntegerField()),
                ('total_weight', models.IntegerField(choices=[(65, '65 Kgs'), (80, '80 Kgs'), (100, '100 Kgs')])),
                ('brokage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(65, '65 Kgs'), (80, '80 Kgs'), (100, '100 Kgs')])),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='mill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='millinfo.Mill'),
        ),
        migrations.AddField(
            model_name='entry',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='millinfo.Party'),
        ),
        migrations.AddField(
            model_name='entry',
            name='weight_per_bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='millinfo.Weight'),
        ),
    ]
