# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mill',
            name='contact_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
