# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millinfo', '0003_auto_20171015_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='total_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weight',
            name='value',
            field=models.IntegerField(),
        ),
    ]
