# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millinfo', '0005_auto_20171015_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.CharField(max_length=400),
        ),
    ]
